import type { VaultListItem } from "./types";

/** Demo vaults — mirrors `prod-example` + stitch prototype states (UI dev only). */
export const MOCK_VAULTS: VaultListItem[] = [
  {
    id: "my-encrypted-notes",
    displayName: "My Encrypted Notes",
    persistence: "closed",
    session: "open",
    storageMode: "encrypted_dir",
    order: 1,
    canSeal: true,
    lastAccessedWhen: "2m ago",
    lastAccessedAt: "2026-06-02T11:58:00Z",
    note: "Daily scratch pad — sync after laptop backup.",
  },
  {
    id: "vault-example-2",
    displayName: "Vault ExaMple 2",
    persistence: "sealed",
    session: null,
    storageMode: "encrypted_dir",
    order: 2,
    canSeal: false,
    lastAccessedWhen: "2 days ago",
    lastAccessedAt: "2026-05-31T10:00:00Z",
    note: "",
  },
  {
    id: "cold-storage",
    displayName: "Cold Storage",
    persistence: "closed",
    session: null,
    storageMode: "encrypted_dir",
    order: 3,
    canSeal: false,
    lastAccessedWhen: "14 days ago",
    lastAccessedAt: "2026-05-19T08:00:00Z",
    note: "",
  },
  {
    id: "personal-photos",
    displayName: "Personal Photos",
    persistence: "sealed",
    session: null,
    storageMode: "encrypted_dir",
    order: 4,
    canSeal: false,
    lastAccessedWhen: "2 days ago",
    lastAccessedAt: "2026-05-31T14:30:00Z",
    note: "RAW exports only; JPEG previews live elsewhere.",
  },
  {
    id: "work-documents",
    displayName: "Work Documents",
    persistence: "closed",
    session: null,
    storageMode: "encrypted_dir",
    order: 5,
    canSeal: false,
    lastAccessedWhen: "2 days ago",
    lastAccessedAt: "2026-05-31T09:15:00Z",
    note: "",
  },
  {
    id: "old-archive",
    displayName: "Old Archive",
    persistence: "sealed",
    session: null,
    storageMode: "encrypted_dir",
    order: 6,
    canSeal: false,
    lastAccessedWhen: "Jan 2023",
    lastAccessedAt: "2023-01-15T12:00:00Z",
    note: "",
  },
  {
    id: "finance-2025",
    displayName: "Finance 2025",
    persistence: "closed",
    session: null,
    storageMode: "encrypted_dir",
    order: 7,
    canSeal: false,
    lastAccessedWhen: "5 days ago",
    lastAccessedAt: "2026-05-28T16:00:00Z",
    note: "Tax receipts + bank CSV exports.",
  },
  {
    id: "medical-records",
    displayName: "Medical Records",
    persistence: "sealed",
    session: null,
    storageMode: "encrypted_dir",
    order: 8,
    canSeal: false,
    lastAccessedWhen: "3 weeks ago",
    lastAccessedAt: "2026-05-12T11:00:00Z",
    note: "",
  },
  {
    id: "dev-secrets",
    displayName: "Dev Secrets",
    persistence: "closed",
    session: "open",
    storageMode: "encrypted_dir",
    order: 9,
    canSeal: true,
    lastAccessedWhen: "18m ago",
    lastAccessedAt: "2026-06-02T11:42:00Z",
    note: "",
  },
  {
    id: "travel-planner",
    displayName: "Travel Planner",
    persistence: "closed",
    session: null,
    storageMode: "encrypted_dir",
    order: 10,
    canSeal: false,
    lastAccessedWhen: "Yesterday",
    lastAccessedAt: "2026-06-01T18:00:00Z",
    note: "",
  },
  {
    id: "daily-journal",
    displayName: "Daily Journal",
    persistence: "closed",
    session: "recovery",
    storageMode: "encrypted_dir",
    order: 11,
    canSeal: false,
    lastAccessedWhen: "4h ago",
    lastAccessedAt: "2026-06-02T08:00:00Z",
    note: "Recovery pending — last good entry 2026-05-28.",
  },
];
