import { LOADING_BUDGET_MS } from "../loading/budget";
import { CORE_RPC_COMMANDS, type CoreRpcCommand } from "./commands";

/** Cheap RPCs (parse, inspect, alias). Never use `0` here. */
const CHEAP_RPC_MS = 10_000;

/**
 * Invoke timeout for every CORE RPC. `satisfies Record<CoreRpcCommand, number>`
 * fails the typecheck if a command is added without a budget.
 * Desktop adds `app_shutdown` / `app_exit` / `pick_directory` in `invoke.ts`.
 */
export const CORE_RPC_TIMEOUT_MS = {
  [CORE_RPC_COMMANDS.APP_VERSION]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.APP_SETTINGS_GET]: LOADING_BUDGET_MS.settingsLoad,
  [CORE_RPC_COMMANDS.APP_SETTINGS_SAVE]: LOADING_BUDGET_MS.settingsSave,
  [CORE_RPC_COMMANDS.APP_SETTINGS_PARSE_TOML]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.APP_SETTINGS_SERIALIZE_TOML]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.LOG_LIST]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.LOG_GET]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.LOG_DELETE]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.LOG_EVENT]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.VAULT_ROOT_RESOLVE]: LOADING_BUDGET_MS.vaultRootResolve,
  [CORE_RPC_COMMANDS.VAULT_ROOT_SETUP_DEFAULT_ROOT]: LOADING_BUDGET_MS.vaultRoot,
  [CORE_RPC_COMMANDS.VAULT_ROOT_SETUP_PATH]: LOADING_BUDGET_MS.vaultRoot,
  [CORE_RPC_COMMANDS.VAULT_ROOT_DEACTIVATE_ALIAS]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_READ_ALIAS]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_DEFAULT_ROOT_STATUS]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_INSPECT_PATH]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_SUGGESTED_CUSTOM_PATH]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_GROUP_LIST]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_CREATE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_UPDATE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_DELETE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_SET_COLLAPSED]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_REORDER]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_REORDER_GROUPED_VAULTS]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_REPAIR]: LOADING_BUDGET_MS.default,
} as const satisfies Record<CoreRpcCommand, number>;
