import { LOADING_BUDGET_MS } from "../loading/budget";
import { CORE_RPC_COMMANDS, type CoreRpcCommand } from "./commands";

/** Cheap RPCs (parse, inspect, alias). Never use `0` here. */
const CHEAP_RPC_MS = 10_000;

/**
 * Invoke timeout for every CORE RPC. `satisfies Record<CoreRpcCommand, number>`
 * fails the typecheck if a command is added without a budget.
 * Desktop adds `app_shutdown` / `app_exit` / `pick_directory` / `pick_file` /
 * `pick_save_file` / `reveal_in_file_manager` / `open_in_terminal` in `invoke.ts`.
 */
export const CORE_RPC_TIMEOUT_MS = {
  [CORE_RPC_COMMANDS.APP_VERSION]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.APP_SETTINGS_GET]: LOADING_BUDGET_MS.settingsLoad,
  [CORE_RPC_COMMANDS.APP_SETTINGS_SAVE]: LOADING_BUDGET_MS.settingsSave,
  [CORE_RPC_COMMANDS.APP_SETTINGS_PARSE_TOML]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.APP_SETTINGS_SERIALIZE_TOML]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.LOG_LIST]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.LOG_GET]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.LOG_DELETE]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.LOG_EVENT]: LOADING_BUDGET_MS.logs,
  [CORE_RPC_COMMANDS.VAULT_ROOT_RESOLVE]: LOADING_BUDGET_MS.vaultRootResolve,
  [CORE_RPC_COMMANDS.VAULT_ROOT_SETUP_DEFAULT_ROOT]: LOADING_BUDGET_MS.vaultRoot,
  [CORE_RPC_COMMANDS.VAULT_ROOT_SETUP_PATH]: LOADING_BUDGET_MS.vaultRoot,
  [CORE_RPC_COMMANDS.VAULT_ROOT_DEACTIVATE_ALIAS]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_READ_ALIAS]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_DEFAULT_ROOT_STATUS]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_INSPECT_PATH]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_ROOT_SUGGESTED_CUSTOM_PATH]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_GROUP_LIST]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_CREATE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_UPDATE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_DELETE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_SET_COLLAPSED]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_REORDER]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_REORDER_GROUPED_VAULTS]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_GROUP_REPAIR]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_LIST]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_CREATE]: LOADING_BUDGET_MS.vaultCreate,
  [CORE_RPC_COMMANDS.VAULT_OPEN]: LOADING_BUDGET_MS.vaultPipeline,
  [CORE_RPC_COMMANDS.VAULT_CLOSE]: LOADING_BUDGET_MS.vaultPipeline,
  [CORE_RPC_COMMANDS.VAULT_CONFIG_GET]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_CONFIG_SAVE]: LOADING_BUDGET_MS.settingsSave,
  [CORE_RPC_COMMANDS.VAULT_RENAME]: LOADING_BUDGET_MS.vaultRename,
  [CORE_RPC_COMMANDS.VAULT_DELETE]: LOADING_BUDGET_MS.vaultDelete,
  [CORE_RPC_COMMANDS.VAULT_RECOVER_ACK]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_EXPORT]: LOADING_BUDGET_MS.vaultExport,
  [CORE_RPC_COMMANDS.VAULT_EXPORT_CAPABILITIES]: CHEAP_RPC_MS,
  /** Argon2id wrap check before packing a `.7z`. Same budget as `vault_open`. */
  [CORE_RPC_COMMANDS.VAULT_EXPORT_PROBE]: LOADING_BUDGET_MS.vaultPipeline,
  [CORE_RPC_COMMANDS.VAULT_IMPORT_ZIP]: LOADING_BUDGET_MS.vaultExport,
  [CORE_RPC_COMMANDS.VAULT_IMPORT_7Z]: LOADING_BUDGET_MS.vaultCreate,
  /** Store-zip probe. `.7z` uses `vaultImportProbeTimeoutMs`. */
  [CORE_RPC_COMMANDS.VAULT_IMPORT_PROBE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_LIST]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_REVISION]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.VAULT_FS_READ]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_READ_RANGE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_WRITE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_WRITE_RANGE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_IMPORT_OS_FILE]: LOADING_BUDGET_MS.vaultFsImport,
  [CORE_RPC_COMMANDS.VAULT_FS_TRUNCATE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_MKDIR]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_CREATE_FILE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_CREATE_FOLDER]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_ENSURE_FOLDER]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_DELETE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_RENAME]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_MOVE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.VAULT_FS_OS_PATH]: CHEAP_RPC_MS,
  [CORE_RPC_COMMANDS.BACKUP_LIST]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.BACKUP_DELETE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.BACKUP_PROMOTE]: LOADING_BUDGET_MS.default,
  [CORE_RPC_COMMANDS.BACKUP_GET]: LOADING_BUDGET_MS.vaultExport,
} as const satisfies Record<CoreRpcCommand, number>;

/** Same rule as the daemon: `seven_zip` / `7z`, or a `.7z` path when kind is omitted. */
export function vaultImportProbeTimeoutMs(params: { kind?: string; archivePath?: string }): number {
  const kind = params.kind?.trim().toLowerCase();
  if (kind === "seven_zip" || kind === "7z") return LOADING_BUDGET_MS.vaultCreate;
  if (!kind && params.archivePath?.trim().toLowerCase().endsWith(".7z")) {
    return LOADING_BUDGET_MS.vaultCreate;
  }
  return CORE_RPC_TIMEOUT_MS[CORE_RPC_COMMANDS.VAULT_IMPORT_PROBE];
}
