/** Tauri command names — extend alongside `dev/src-tauri/src/lib.rs` handlers. */
export const TAURI_COMMANDS = {
  APP_VERSION: "app_version",
  APP_EXIT: "app_exit",
  VAULT_ROOT_FROM_ENV: "vault_root_from_env",
  VAULT_ROOT_AUTO_DETECT: "vault_root_auto_detect",
  VAULT_ROOT_IS_VALID: "vault_root_is_valid",
  VAULT_ROOT_INITIALIZE: "vault_root_initialize",
  VAULT_ROOT_DEV_FALLBACK: "vault_root_dev_fallback",
  APP_VAULT_ROOT_PATH_GET: "app_vault_root_path_get",
  APP_VAULT_ROOT_PATH_SET: "app_vault_root_path_set",
  APP_SETTINGS_GET: "app_settings_get",
  APP_SETTINGS_SAVE: "app_settings_save",
  VAULT_LIST: "vault_list",
  VAULT_CONFIG_GET: "vault_config_get",
  VAULT_CONFIG_SAVE: "vault_config_save",
  VAULT_CREATE: "vault_create",
  VAULT_REORDER: "vault_reorder",
  VAULT_DELETE: "vault_delete",
  VAULT_CHANGE_PASSWORD: "vault_change_password",
  VAULT_RECOVERY_ASSESS: "vault_recovery_assess",
  VAULT_RECOVERY_RESOLVE: "vault_recovery_resolve",
  BACKUP_LIST: "backup_list",
  BACKUP_DELETE: "backup_delete",
  BACKUP_PROMOTE_SAVE: "backup_promote_save",
  BACKUP_READ_BYTES: "backup_read_bytes",
  VAULT_ARCHIVE_BYTES: "vault_archive_bytes",
  LOG_LIST: "log_list",
  LOG_GET: "log_get",
  LOG_DELETE: "log_delete",
  LOG_APPEND: "log_append",
  OPEN_PATH_IN_FILE_MANAGER: "open_path_in_file_manager",
  VAULT_DISK_SESSION_EXISTS: "vault_disk_session_exists",
  VAULT_DISK_SESSION_READ: "vault_disk_session_read",
  PICK_VAULT_ROOT_FOLDER: "pick_vault_root_folder",
  PLAIN_VAULT_OPEN: "plain_vault_open",
  PLAIN_VAULT_CLOSE: "plain_vault_close",
  ENCRYPTED_VAULT_OPEN: "encrypted_vault_open",
  ENCRYPTED_VAULT_CLOSE: "encrypted_vault_close",
  ENCRYPTED_VAULT_SEAL_CLOSED: "encrypted_vault_seal_closed",
  VAULT_WORKSPACE_MOUNT_STATUS: "vault_workspace_mount_status",
  WORKSPACE_SNAPSHOT: "workspace_snapshot",
  WORKSPACE_WRITE_FILE: "workspace_write_file",
  WORKSPACE_MAKE_DIR: "workspace_make_dir",
  WORKSPACE_IMPORT_FOLDER: "workspace_import_folder",
  WORKSPACE_DELETE: "workspace_delete",
  WORKSPACE_RENAME: "workspace_rename",
  WORKSPACE_MOVE: "workspace_move",
  WORKSPACE_WATCH_START: "workspace_watch_start",
  WORKSPACE_WATCH_STOP: "workspace_watch_stop",
} as const;

/** Tauri event emitted when the workspace directory changes on disk. */
export const TAURI_EVENTS = {
  WORKSPACE_CHANGED: "workspace-changed",
} as const;

export type TauriCommand = (typeof TAURI_COMMANDS)[keyof typeof TAURI_COMMANDS];
