/** Glyph catalog shared by desktop SVG and mobile `react-native-svg` `Icon` components. */
export const ICON_NAMES = [
  "add",
  "archive",
  "arrow-down",
  "arrow-up",
  "backups",
  "chevron-down",
  "clock",
  "close",
  "cpu",
  "download",
  "encrypted",
  "eye",
  "eye-off",
  "file",
  "file-manager",
  "grip-vertical",
  "folder",
  "help",
  "history",
  "info",
  "lock",
  "minus",
  "lock-open",
  "more-horizontal",
  "more-vertical",
  "note",
  "layout-grid",
  "layers",
  "list-rows",
  "list-rows-loose",
  "list-rows-tight",
  "refresh",
  "search",
  "sort-alpha",
  "sort-state",
  "settings",
  "sort",
  "terminal",
  "trash",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
