export {
  RESERVED_UPRIV_WORKSPACE_CHILDREN,
  type ReservedUprivWorkspaceChild,
  type WorkspacePathIssue,
} from "./types";
export {
  WORKSPACE_SYSTEMS,
  appWorkspace,
  currentWorkspaceSystem,
  detectHostPlatform,
  appWorkspacePlace,
  encryptedShortcutActive,
  hostPlatformFromSignals,
  normalizeWorkspaceTable,
  resolvedWorkspaceParent,
  vaultMountForDaemon,
  vaultWorkspace,
  workspaceSystemFromHost,
  workspaceSystemHasShortcut,
  workspaceSystemsCurrentFirst,
  workspaceTablesEqual,
  type NavigatorHostSignals,
  type VaultShortcut,
  type WorkspaceOsEntry,
  type WorkspacePlace,
  type WorkspaceSystem,
  type WorkspaceTable,
} from "./os";
export {
  isAbsoluteFilesystemPath,
  isAbsoluteOsFilesystemPath,
  isContentUri,
  isReservedUprivWorkspacePath,
  safTreeUriHasExtraSegment,
  normalizeWorkspaceGlobalPath,
  resolveVaultMountPoint,
  sanitizeMountLeaf,
  suggestedDefaultWorkspacePath,
  workspaceContainerPath,
  validateWorkspaceGlobalPath,
  validateWorkspaceTable,
  vaultRootPathForWorkspaceValidation,
} from "./validate";
export {
  WORKSPACE_ERROR_CODES,
  WORKSPACE_ERROR_I18N,
  WORKSPACE_PATH_ISSUE_I18N,
  isWorkspaceErrorCode,
  workspaceErrorI18nKey,
  workspacePathIssueI18nKey,
  type WorkspaceErrorCode,
} from "./errors";
